export { default as Button } from "./Button";
export { default as Project } from "./Project";
export { default as Modal } from "./Modal";
export { default as Navbar } from "./Navbar";
export { default as Card } from "./Card";
export { default as Skills } from "./Skills";
export { default as Contact } from "./Contact";
export { default as Input } from "./Input";
export { default as TextArea } from "./Textarea";
